### ISSUE TITLE
mnist dataset LMDB?

### ISSUE THREAD

**Issue by soumith** [potterhsu/MnistTensorFlowVsPyTorch#1]
We dont need to use something as heavy as LMDB for MNIST.
MNIST is available in [torchvision](https://github.com/pytorch/vision) as a ready-to-use dataset.

**Comment by potterhsu** [comment]
Yes, torchvision is indeed great and convenience.
However, as I use TFRecords instead of the off-the-shelf MNIST dataset module (something like `from tensorflow.examples.tutorials.mnist import input_data`) in TensorFlow.
What I need is a standard format which can be an interface of all other datasets and even custom dataset.
That's why I decide to use LMDB.

**Comment by soumith** [comment]
ok, sure. Generally, we dont use lmdb for any datasets except LSUN just so you know (and we have 10+ datasets under vision)
